### ISSUE TITLE
Windows unit test failures

### ISSUE THREAD

**Issue by springmeyer** [mapnik/mapnik#3359]
I've got the windows builds working again on appveyor as of this afternoon. Now we are actually getting to the test runs but I'm seeing failures:

```
csv
  broken files
-------------------------------------------------------------------------------
..\..\test\unit\datasource\csv.cpp(84)
...............................................................................
 
..\..\test\unit\datasource\csv.cpp(153): FAILED:
  REQUIRE_THROWS( get_csv_ds(path) )
because no exception was thrown where one was expected:
  test/data/csv/warns\feature_id_counting.csv
 
Completed in 0.228424s
csv completed in 0s
-------------------------------------------------------------------------------
csv
  good files
-------------------------------------------------------------------------------
..\..\test\unit\datasource\csv.cpp(84)
...............................................................................
 
..\..\test\unit\datasource\csv.cpp(193): FAILED:
  CHECK( mapnik::util::exists(path + ".index") )
with expansion:
  false
with messages:
  0
  0
 
Completed in 40.5926s
csv
  creation of CSV from in-memory strings
-------------------------------------------------------------------------------
..\..\test\unit\datasource\csv.cpp(84)
...............................................................................
 
..\..\test\unit\datasource\csv.cpp(879): FAILED:
  CHECK( feature->get("Name") == ustring(name.c_str()) )
with expansion:
  Québec == {?}
 
Completed in 0.000793s

image io
  image_util : save_to_file/save_to_stream/save_to_string
-------------------------------------------------------------------------------
..\..\test\unit\imaging\image_io_test.cpp(19)
...............................................................................
 
..\..\test\unit\imaging\image_io_test.cpp(121): FAILED:
due to unexpected exception with message:
  Could not write file to /tmp/mapnik-lightblue.png
 

```

**Comment by BergWerkGIS** [comment]
Additionally I get

<pre>
csv
  good files
-------------------------------------------------------------------------------
..\..\test\unit\datasource\csv.cpp(85)
...............................................................................

..\..\test\unit\datasource\csv.cpp(194): FAILED:
  CHECK( mapnik::util::exists(path + ".index") )
with expansion:
  false
with messages:
<b>  0 <=========== ret = create_disk_index(path);
  0 <=========== ret_posix = (ret >> 8) & 0x000000ff;</b>
</pre>

Because `mapnik-index` doesn't create an index and doesn't return `!=0`.

```
processing 'test/data/csv\more_headers_than_column_values.csv' as CSV
Mapnik LOG> 2016-03-12 08:03:48: CSV Plugin: # of columns(2) < # of headers(5) parsed at line: 2
done!
```

```
λ mapnik-index test\data\csv\more_headers_than_column_values.csv
max tree depth:8
split ratio:0.55
processing 'test\data\csv\more_headers_than_column_values.csv' as CSV
Mapnik LOG> 2016-03-12 08:29:37: CSV Plugin: # of columns(2) < # of headers(5) parsed at line: 2
done!
λ ECHO %ERRORLEVEL%
0
λ dir test\data\csv\more_headers_than_column_values.*
03/12/2016  06:57 AM                22 more_headers_than_column_values.csv
               1 File(s)             22 bytes
               0 Dir(s)  46,328,193,024 bytes free
```

/cc @artemp maybe again some Windows line feed parsing issue?

same for
* `test\data\csv\quoted_numbers-mixed.csv`
* `test\data\csv\quoted_numbers-mixed2.csv`
* `test\data\csv\unicode.tsv`

----

`Québec` test case looks a bit different (also different line at 887 vs 879 above):

<pre>
..\..\test\unit\datasource\csv.cpp<b>(887)</b>: FAILED:
  CHECK( feature->get("Name") == val )
with expansion:
  Québec == Qu??bec
with messages:
<b>  Québec <=========== INFO(feature->get("Name"));
  Qu??bec <=========== INFO(utf8);
  Qu??bec <=========== INFO(val);</b>
</pre>

-----


Not getting `Could not write file to /tmp/mapnik-lightblue.png`, but

<pre>
image io
  image_util : save_to_file/save_to_stream/save_to_string
-------------------------------------------------------------------------------
..\..\test\unit\imaging\image_io_test.cpp(27)
...............................................................................

..\..\test\unit\imaging\image_io_test.cpp(129): FAILED:
  {Unknown expression after the reported line}
due to unexpected exception with message:
<b>  boost::filesystem::remove: The process cannot access the file because it is
  being used by another process: "/tmp/mapnik-tests/mapnik-lightblue.png"</b>
</pre>

**Comment by springmeyer** [comment]
Thanks for the help @lightmare (https://github.com/mapnik/mapnik/commit/c18e086026f5030fd53cad5ff80cb250e271f55b#commitcomment-16661192). Makes sense now that I think we need to transcode before comparing which I just pushed https://github.com/mapnik/mapnik/commit/2204a983c628442e8ce6366a200823e8bbd5f14e

@BergWerkGIS thanks for the rundown of errors. Another is non portable path comparison which fails due to `/` vs `\`. It looks like `boost::filesystem` directory iterator will end up spitting out paths like `c:\this\that/filename.csv`. I could not see a way with boost to normalize back to unix style paths to compare so I resorted to just looking at the filename with `boost::iends_with` to mimic the previous logic.

> boost::filesystem::remove: The process cannot access the file because it is
  being used by another process: "/tmp/mapnik-tests/mapnik-lightblue.png"

Yes, a new one unmasked by fixing the previous problem of the `/tmp` directory not existing on appveyor. This one I think should be solved by letting go of the reader: https://github.com/mapnik/mapnik/commit/632dd7e76d0f13d68b2e7c260e0162071c3e6c51

Watching appveyor now to see if we get 100% passing....

**Comment by springmeyer** [comment]
> All tests passed (22703 assertions in 55 test cases)

:boom:

**Comment by springmeyer** [comment]
Whoops, visual tests are still failing, so re-opening. I notice they are trying to be run at `mapnik-gyp\build\Release\test_visual_run.exe` but the unit test is at `mapnik-gyp\build\test\test.exe`. @BergWerkGIS is the `Release` directory incorrect? Instead of me committing with guesses I'll kick this back to you to test locally to ensure it works the way you have designed.

**Comment by BergWerkGIS** [comment]
Still getting `csv` test failures locally (I've added `INFO(path)`):

<pre>
csv
  good files
-------------------------------------------------------------------------------
..\..\test\unit\datasource\csv.cpp(85)
...............................................................................

..\..\test\unit\datasource\csv.cpp(195): FAILED:
  CHECK( mapnik::util::exists(path + ".index") )
with expansion:
  false
with messages:
  0
  0
<b>  test/data/csv\quoted_numbers-mixed.csv</b>

..\..\test\unit\datasource\csv.cpp(195): FAILED:
  CHECK( mapnik::util::exists(path + ".index") )
with expansion:
  false
with messages:
  0
  0
  <b>test/data/csv\quoted_numbers-single.csv</b>
</pre>

-----

#### Mapnik LOGs:
<pre>
processing <b>'test/data/csv\quoted_numbers-mixed.csv'</b> as CSV
Mapnik LOG> 2016-03-14 09:48:03: CSV Plugin: # of columns(4) > # of headers(3) parsed at line: 2
Mapnik LOG> 2016-03-14 09:48:03: CSV Plugin: # of columns(4) > # of headers(3) parsed at line: 3
Mapnik LOG> 2016-03-14 09:48:03: CSV Plugin: # of columns(4) > # of headers(3) parsed at line: 4
Mapnik LOG> 2016-03-14 09:48:03: CSV Plugin: # of columns(4) > # of headers(3) parsed at line: 5
Mapnik LOG> 2016-03-14 09:48:03: CSV Plugin: # of columns(4) > # of headers(3) parsed at line: 6
done!
</pre>

<pre>
processing <b>'test/data/csv\quoted_numbers-single.csv'</b> as CSV
Mapnik LOG> 2016-03-14 09:48:03: CSV Plugin: # of columns(4) > # of headers(3) parsed at line: 2
Mapnik LOG> 2016-03-14 09:48:03: CSV Plugin: # of columns(4) > # of headers(3) parsed at line: 3
Mapnik LOG> 2016-03-14 09:48:03: CSV Plugin: # of columns(4) > # of headers(3) parsed at line: 4
Mapnik LOG> 2016-03-14 09:48:03: CSV Plugin: # of columns(4) > # of headers(3) parsed at line: 5
Mapnik LOG> 2016-03-14 09:48:03: CSV Plugin: # of columns(4) > # of headers(3) parsed at line: 6
done!
</pre>

-----

**If I change the line endings of**
* `test/data/csv\quoted_numbers-mixed.csv` and 
* `test/data/csv\quoted_numbers-single.csv` 

**to `LF` csv tests succeed!**

/cc @artemp 

----

> Whoops, visual tests are still failing, so re-opening. I notice they are trying to be run at `mapnik-gyp\build\Release\test_visual_run.exe` but the unit test is at `mapnik-gyp\build\test\test.exe`. @BergWerkGIS is the `Release` directory incorrect?

Paths are correct, visual tests [weren't being built yet on AppVeyor](https://github.com/mapnik/mapnik-gyp/blob/dc8329937d7f9cf4a985ac0ab4a00fe1a9596957/build.bat#L606) as I was still struggling to even get that far. :smirk: 
Working on it.

**Comment by BergWerkGIS** [comment]
With the current setting of `%NUMBER_OF_PROCESSORS% - 2` for visual tests jobs `test_visual_run.exe` crashed:

```
==== visual tests ===
visual tests agg
ERROR 7: Assertion `FALSE' failed
in file `gdaldrivermanager.cpp', line 415
```

After setting jobs back to **1** `test_visual_run.exe` runs thru, but a few tests are still failing:

e.g.
![image](https://cloud.githubusercontent.com/assets/4549888/13741979/267e0400-e9d1-11e5-8fd5-fe866631ed26.png)
visual diff:
![image](https://cloud.githubusercontent.com/assets/4549888/13741988/36372b7e-e9d1-11e5-8070-c62811b94e78.png)

----

Appveyor is now green and _"passing tests"_ as we currently don't bail on failed tests.
I think **we should change this behavior ASAP.**

Even PostGIS tests are working: Postgres service gets started manually and PostGIS gets installed manually.

5 visual tests are failing:
https://ci.appveyor.com/project/Mapbox/mapnik/build/1.0.815#L1488

**Comment by springmeyer** [comment]
> With the current setting of %NUMBER_OF_PROCESSORS% - 2 for visual tests jobs test_visual_run.exe crashed:

@BergWerkGIS okay, I bumped the # back up in hopes that https://github.com/mapnik/mapnik/commit/d4566c28d21a90f490adbccd528b82115b71d0a5 had fixed. Can you also try applying: https://github.com/mapnik/mapnik/pull/3345

**Comment by springmeyer** [comment]
@BergWerkGIS let's track that tiff-reprojection failure at https://github.com/mapnik/mapnik/issues/2438

**Comment by springmeyer** [comment]
> Even PostGIS tests are working: Postgres service gets started manually and PostGIS gets installed manually.

That is fantastic.

> I think we should change this behavior ASAP.

Yes, I agree.

> 5 visual tests are failing:

Can you make the appveyor build automatically upload the visual test results directory to s3? You could put them at https://s3.amazonaws.com/mapnik/dist/dev/visual-results/{appveyor build id}?

**Comment by BergWerkGIS** [comment]
> upload the visual test results directory to s3?

Will do. Good idea. I already thought about adding them as AppVeyor artifact but discarded the idea, because that directory weighs in at +90MB (still at +30MB with `7z` at maximum compression).

**Comment by springmeyer** [comment]
> that directory weighs in at +90MB (still at +30MB with 7z at maximum compression).

@BergWerkGIS Are we talking about the same time? I'm referring to uploading the test results (when there failures) which should be quite small when there are only a few failures. If you run `./test/visual/run -h` (or `mapnik-gyp\build\Release\test_visual_run.exe -h` on windows) you will see `--output-dir arg (=/tmp/mapnik-visual-images)` which is what we'd upload.

**Comment by BergWerkGIS** [comment]
@springmeyer ah, you are right, quite small indeed. Interesting.

Is there some clean up going on after successful tests?
Maybe I checked right after `test_visual_run.exe` had crashed.

**Comment by springmeyer** [comment]
> Is there some clean up going on after successful tests?

Not that I'm aware (because we write to /tmp we assume that gets cleaned up occasionally by the OS) - so perhaps locally you are accumulating a lot of failure data. Perhaps we could manually clear at the start of a new run or we could start using an official temp directory on windows: http://www.boost.org/doc/libs/1_46_0/libs/filesystem/v3/doc/reference.html#temp_directory_path

**Comment by BergWerkGIS** [comment]
> we write to /tmp we assume that gets cleaned up occasionally by the OS

I'm not aware of any temp directory on Windows that gets cleaned up automatically per default.
If you write there you have to delete your stuff yourself afterwards.


> or we could start using an official temp directory on windows

Y, would be the proper OS specific approach but it's often difficult to manually find the directory.
There are at least 3 to 5 different temp folders, depending on several factors (user and permissions) and how you ask for them.

I'm fine with `/tmp` -> easy to find.

No problem to do some cleaning before a new run.

Little reminder: sometimes we have a race condition when building x86 and x64 at the same time (`[build32bit]`) and both build processes read/write the same files.

**Comment by springmeyer** [comment]
> Little reminder: sometimes we have a race condition when building x86 and x64 at the same time ([build32bit]) and both build processes read/write the same files.

@BergWerkGIS the `--output-dir` argument was added to be able to customize the path when the tests are run. We should be using that to workaround the windows-build problem. Can you ticket at windows-builds?

**Comment by artemp** [comment]
@BergWerkGIS - can replicate, will push fix tomorrow.

**Comment by BergWerkGIS** [comment]
> Can you ticket at windows-builds?

Ticketed here: https://github.com/mapnik/mapnik-gyp/issues/27

@artemp great, thanks.

**Comment by BergWerkGIS** [comment]
@springmeyer visual test results added to AppVeyor artifacts:
e.g. https://ci.appveyor.com/project/Mapbox/mapnik/build/1.0.829/artifacts

**Comment by artemp** [comment]
tests https://github.com/mapnik/test-data/commit/8bf0d18da9c716fe33905893d81818d5632070a9

**Comment by lightmare** [comment]
> or we could start using an official temp directory on windows: http://www.boost.org/doc/libs/1_46_0/libs/filesystem/v3/doc/reference.html#temp_directory_path

That's what I did in lazy demultiply tests. It even honors environment overrides TMPDIR et al.
